Initialize extra_args to None
Upstream rpkg added extra_args via

    commit fe638de275182cf9302eb42aecd327e01854969b
    Author: Ondrej Nosek <onosek@redhat.com>
    Date:   Tue Apr 28 09:48:33 2020 +0200

        Passing additional arguments to underlaying commands

Update the client object to include this to ensure it exists.
Fixes the following traceback:

Traceback (most recent call last):
  File "./kernel-git.py", line 411, in <module>
    create_tree(sha, nvrtag)
  File "./kernel-git.py", line 293, in create_tree
    fedcli.args.command()
  File "/usr/lib/python3.8/site-packages/pyrpkg/cli.py", line 2542, in prep
    extra_args=self.extra_args,
AttributeError: 'fedpkgClient' object has no attribute 'extra_args'